# Generated by Django 5.2.7 on 2025-11-21 19:45

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_codeusage_alter_paymentverificationcode_options_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeusage',
            options={'ordering': ['-used_at'], 'verbose_name': 'Utilisation de code', 'verbose_name_plural': 'Utilisations de codes'},
        ),
        migrations.AddField(
            model_name='codeusage',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text="Détails supplémentaires sur l'utilisation", verbose_name='Détails'),
        ),
        migrations.AddField(
            model_name='codeusage',
            name='success',
            field=models.BooleanField(default=True, help_text='Indique si la tentative a réussi', verbose_name='Réussite'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='code_type',
            field=models.CharField(choices=[('certification', 'Certification'), ('promotion', 'Promotion produit')], db_index=True, default='certification', max_length=20, verbose_name='Type de code'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', '%'), ('fixed', 'FCFA')], default='percentage', help_text='Type de réduction (pourcentage ou montant fixe)', max_length=10, verbose_name='Type de réduction'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valeur de la réduction (en pourcentage ou montant fixe)', max_digits=10, null=True, verbose_name='Valeur de la réduction'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour les codes promotionnels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to='stores.product', verbose_name='Produit associé'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='code',
            field=models.CharField(db_index=True, default=payments.models.generate_verification_code, max_length=20, unique=True, verbose_name='Code de vérification'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour les codes de certification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='payments.storesubscription', verbose_name='Abonnement associé'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_codes', through='payments.CodeUsage', through_fields=('code', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Utilisé par'),
        ),
        migrations.AddIndex(
            model_name='codeusage',
            index=models.Index(fields=['code', 'used_at'], name='payments_co_code_id_660368_idx'),
        ),
        migrations.AddIndex(
            model_name='codeusage',
            index=models.Index(fields=['user', 'used_at'], name='payments_co_user_id_9cb72d_idx'),
        ),
        migrations.AddIndex(
            model_name='codeusage',
            index=models.Index(fields=['success', 'used_at'], name='payments_co_success_2d5e60_idx'),
        ),
    ]
