# Generated by Django 5.2.7 on 2025-11-25 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_class_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
