# Generated by Django 5.2.7 on 2025-11-21 02:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money'), ('mtn', 'MTN Mobile Money'), ('wave', 'Wave')], max_length=20, unique=True)),
                ('sms_sender', models.CharField(help_text="Numéro ou nom d'expéditeur des SMS (ex: Orange, Moov)", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_regex_pattern', models.TextField(help_text='Expression régulière pour extraire les données du SMS. Doit contenir des groupes nommés: amount, phone, code')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('api_base_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuration Mobile Money',
                'verbose_name_plural': 'Configurations Mobile Money',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration in days')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('features', models.JSONField(default=list, verbose_name='Features')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='ID de transaction')),
                ('payment_method', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('wave', 'Wave'), ('paypal', 'PayPal'), ('carte', 'Carte Bancaire')], max_length=20, verbose_name='Méthode de paiement')),
                ('service_type', models.CharField(choices=[('store', 'Boutique'), ('promo', 'Promotion'), ('certif', 'Certification'), ('formation', 'Formation')], default='store', max_length=20, verbose_name='Type de service')),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID de la formation, certification, etc.', null=True, verbose_name='ID de référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Payment'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscriptions', to='stores.store')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Store Subscription',
                'verbose_name_plural': 'Store Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=payments.models.generate_verification_code, max_length=14, unique=True, verbose_name='Verification Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='payments.storesubscription')),
            ],
            options={
                'verbose_name': 'Payment Verification Code',
                'verbose_name_plural': 'Payment Verification Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='payments_pa_code_6a6f3f_idx'), models.Index(fields=['status'], name='payments_pa_status_5c5b2c_idx')],
            },
        ),
    ]
