# Generated by Django 5.2.7 on 2025-11-21 18:55

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'utilisation")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Utilisation de code',
                'verbose_name_plural': 'Historique des utilisations de codes',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='paymentverificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code de vérification', 'verbose_name_plural': 'Codes de vérification'},
        ),
        migrations.RemoveIndex(
            model_name='paymentverificationcode',
            name='payments_pa_code_6a6f3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentverificationcode',
            name='payments_pa_status_5c5b2c_idx',
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentatives échouées'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière tentative'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Nombre maximum de tentatives de validation avant blocage', verbose_name='Nombre maximum de tentatives'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de fois que ce code a été utilisé', verbose_name="Nombre d'utilisations"),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1, help_text='Nombre maximum de fois que ce code peut être utilisé (0 pour illimité)', verbose_name="Nombre maximum d'utilisations"),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='code',
            field=models.CharField(db_index=True, default=payments.models.generate_verification_code, max_length=14, unique=True, verbose_name='Code de vérification'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='expires_at',
            field=models.DateTimeField(db_index=True, help_text='Date à laquelle ce code expirera automatiquement', verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='notes',
            field=models.TextField(blank=True, help_text='Informations supplémentaires sur ce code', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='payments.storesubscription', verbose_name='Abonnement associé'),
        ),
        migrations.AlterField(
            model_name='paymentverificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation"),
        ),
        migrations.RemoveField(
            model_name='paymentverificationcode',
            name='used_by',
        ),
        migrations.AddField(
            model_name='codeusage',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_usages', to='payments.paymentverificationcode', verbose_name='Code de vérification'),
        ),
        migrations.AddField(
            model_name='codeusage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_usage_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='paymentverificationcode',
            index=models.Index(fields=['code', 'status'], name='payments_pa_code_c39452_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentverificationcode',
            index=models.Index(fields=['expires_at', 'status'], name='payments_pa_expires_82ace7_idx'),
        ),
        migrations.AddField(
            model_name='paymentverificationcode',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_codes', through='payments.CodeUsage', to=settings.AUTH_USER_MODEL, verbose_name='Utilisé par'),
        ),
    ]
