# Generated by Django 5.2.7 on 2025-11-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_code_type_to_paymentverificationcode'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(default='+22601256984', help_text='Numéro de téléphone WhatsApp au format international (ex: +226012345678)', max_length=20, verbose_name='Numéro WhatsApp par défaut')),
                ('api_key', models.CharField(blank=True, help_text="Clé d'API pour l'envoi de messages WhatsApp", max_length=255, verbose_name='Clé API')),
                ('api_url', models.URLField(default='https://api.whatsapp.com/send', help_text="URL de base de l'API WhatsApp", verbose_name="URL de l'API")),
                ('is_active', models.BooleanField(default=True, help_text="Activer/désactiver l'envoi de messages WhatsApp", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Configuration WhatsApp',
                'verbose_name_plural': 'Configurations WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Numéro de téléphone au format international', max_length=20, verbose_name='Destinataire')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('status_updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='stores.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Message WhatsApp',
                'verbose_name_plural': 'Messages WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
